extends:
  - airbnb

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

settings:
  import/resolver:
    - node
    - webpack

rules:
  import/prefer-default-export: 0
  import/extensions: 0
