---

default: &default
  type: postgres
  host: db
  username: postgres
  # encoding: unicode

development:
  <<: *default
  type: sqlite
  database: db/development.sqlite3

test:
  <<: *default
  type: sqlite
  database: db/test.sqlite3

# production:
#   <<: *default
#   url: <%= ENV['DATABASE_URL'] %>
