name: On Pull Request

on:
  pull_request:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          make install
      - name: Run lint
        run: |
          make lint
      - name: Run tests
        run: |
          make test
