name: On Push

on:
  push:
    branches:
      - master

jobs:

  build:
    if: github.repository == 'hexlet/hexlet-editor'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          make install
      - name: Run lint
        run: |
          make lint
